title: "Swiss ISA Hub"
description: "Non-profit association in Switzerland."
url: "https://swissisahub.org"
baseurl: ""
lang: en-GB
theme: minima

# Navigation (Minima)
header_pages:
  - about.md
  - members.md
  - contacts.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  input: GFM
